---
# tasks file for nginx
- name: Ensure Nginx Release Repo Installed
  yum: name={{ nginx }}
  become: yes

- name: Ensure Nginx Latest Release Installed
  yum: name=nginx state=latest
  become: yes  

- name: Ensure Nginx Service Running and Enabled
  service: name=nginx state=started enabled=yes
  become: yes

- name: Deploy Customized Home Page 
  copy:
    src: nginx_home.html
    dest: /usr/share/nginx/html/index.html
  become: yes
#- name: Nginx Sanity Checks
  #hosts: app 


- name: Check port 80 and fail otherwise
  wait_for:
    port: 80
    connect_timeout: 1
    timeout: 5

- name: Check nginx configuration is correct
  command: /usr/sbin/nginx -t
  register: nginx_validate
  changed_when: no
  ignore_errors: yes
  become: yes